
name: Continuous Integration  #Nome Workflow (Fluxo de Trabalho)
on: #Define em que momento fluxo será Rodado"Ativado / Acionado"
    pull_request:
       branches:
         - main

jobs: #Tarefa / Serviço a ser executado
  build:
    runs-on: ubuntu-latest #Usa uma maquina (Linux) para fazer os passos
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        #Apartir daqui pode ser incluidas outras Actions
      - name: Python Lint Code Scanning Action
        uses: advanced-security/python-lint-code-scanning-action@v1.1.2
        with:
          linter: pylint